replicaCount: 2
applicationName: web-app
terminationGracePeriodSeconds: 30

image:
  repository: 013335838002.dkr.ecr.us-east-2.amazonaws.com/web-app
  tag: v1.0.2
  pullPolicy: Always

containerPort: 3000

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

deploymentAnnotations:
  keel.sh/pollSchedule: "@every 5m"
  keel.sh/trigger: poll
  keel.sh/policy: all
