apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "youtube-clone-chart.fullname" . }}
  labels:
    app: {{ include "youtube-clone-chart.name" . }}
{{- with .Values.deploymentAnnotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "youtube-clone-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "youtube-clone-chart.name" . }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Values.applicationName }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
